### ISSUE TITLE
end and nether are broken

### ISSUE THREAD

**Issue by efor89** [Benedikt05/BetterAltay#11]
### Issue description

hi the end and nether are very bugi the blocks disappear if i klick on it.  
i try it with pmmp is the same.

### Steps to reproduce the issue
1. create end or nether
2. go to end or nether
3. klick on block

### OS and versions
* Altay: 3.26.1-Fix1
* PHP: 8.0
* Using JIT: no
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

multiworld

**Comment by Benedikt05** [comment]
I've already noticed that. Has something with 1.18. I'll see if I can fix this. Thanks for your report.

**Comment by DRAGKILLS** [comment]
> ### Issue description
> hi the end and nether are very bugi the blocks disappear if i klick on it. i try it with pmmp is the same.
> 
> ### Steps to reproduce the issue
> 1. create end or nether
> 2. go to end or nether
> 3. klick on block
> 
> ### OS and versions
> * Altay: 3.26.1-Fix1
> * PHP: 8.0
> * Using JIT: no
> * Server OS:
> * Game version: Android/iOS/Win10/Xbox/PS4/Switch
> 
> ### Plugins
> multiworld

Normal thing its also in pm and i think u can fix it with the nbt thing / files

**Comment by DRAGKILLS** [comment]
I will try to fix it i did i will close it

**Comment by Benedikt05** [comment]
https://github.com/Benedikt05/BetterAltay/tree/nether/end-fix

**Comment by efor89** [comment]
i try it but i become this error is the bin folder not up to date?

[ERROR] Composer autoloader not found at C:\Users\Dennis\Desktop\Altay-stable/vendor/autoload.php
[ERROR] Please install/update Composer dependencies or use provided builds.

**Comment by HanifWadowskyy** [comment]
use composer install --no-dev

**Comment by efor89** [comment]
idn ^^

**Comment by efor89** [comment]
ok have thx

**Comment by efor89** [comment]
thx nether and end work now gj

**Comment by VaxPex** [comment]
Fixed?

**Comment by efor89** [comment]
@Benedikt05 
In the new version the nether and end is not fixed!

**Comment by VaxPex** [comment]
no

**Comment by VaxPex** [comment]
In future the hack will be prevented and im searching a way to fix it without a hack

**Comment by Benedikt05** [comment]
> In future the hack will be prevented and im searching a way to fix it without a hack

exactly

**Comment by VaxPex** [comment]
Close

**Comment by efor89** [comment]
why close?

**Comment by RizkyPMC** [comment]
wow
